/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcessHaccpRouteImport } from './routes/process-haccp'
import { Route as PackagingRouteImport } from './routes/packaging'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LabelingRouteImport } from './routes/labeling'
import { Route as LabAverageRouteImport } from './routes/lab-average'
import { Route as IngredientsClaimsRouteImport } from './routes/ingredients-claims'
import { Route as FlavouringsRouteImport } from './routes/flavourings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AllergensRouteImport } from './routes/allergens'
import { Route as AdditivesRouteImport } from './routes/additives'
import { Route as ProductsRouteRouteImport } from './routes/products.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as AdditivesIdRouteImport } from './routes/additives_.$id'

const ProcessHaccpRoute = ProcessHaccpRouteImport.update({
  id: '/process-haccp',
  path: '/process-haccp',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingRoute = PackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelingRoute = LabelingRouteImport.update({
  id: '/labeling',
  path: '/labeling',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAverageRoute = LabAverageRouteImport.update({
  id: '/lab-average',
  path: '/lab-average',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsClaimsRoute = IngredientsClaimsRouteImport.update({
  id: '/ingredients-claims',
  path: '/ingredients-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavouringsRoute = FlavouringsRouteImport.update({
  id: '/flavourings',
  path: '/flavourings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AllergensRoute = AllergensRouteImport.update({
  id: '/allergens',
  path: '/allergens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditivesRoute = AdditivesRouteImport.update({
  id: '/additives',
  path: '/additives',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AdditivesIdRoute = AdditivesIdRouteImport.update({
  id: '/additives_/$id',
  path: '/additives/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/additives/$id': typeof AdditivesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/additives/$id': typeof AdditivesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products': typeof ProductsRouteRouteWithChildren
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/additives_/$id': typeof AdditivesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/documents'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/additives/$id'
    | '/products/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/documents'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/additives/$id'
    | '/products/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/products'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/documents'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/additives_/$id'
    | '/products/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  AdditivesRoute: typeof AdditivesRoute
  AllergensRoute: typeof AllergensRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FlavouringsRoute: typeof FlavouringsRoute
  IngredientsClaimsRoute: typeof IngredientsClaimsRoute
  LabAverageRoute: typeof LabAverageRoute
  LabelingRoute: typeof LabelingRoute
  NutritionRoute: typeof NutritionRoute
  PackagingRoute: typeof PackagingRoute
  ProcessHaccpRoute: typeof ProcessHaccpRoute
  AdditivesIdRoute: typeof AdditivesIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/process-haccp': {
      id: '/process-haccp'
      path: '/process-haccp'
      fullPath: '/process-haccp'
      preLoaderRoute: typeof ProcessHaccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging': {
      id: '/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof PackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labeling': {
      id: '/labeling'
      path: '/labeling'
      fullPath: '/labeling'
      preLoaderRoute: typeof LabelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-average': {
      id: '/lab-average'
      path: '/lab-average'
      fullPath: '/lab-average'
      preLoaderRoute: typeof LabAverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients-claims': {
      id: '/ingredients-claims'
      path: '/ingredients-claims'
      fullPath: '/ingredients-claims'
      preLoaderRoute: typeof IngredientsClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavourings': {
      id: '/flavourings'
      path: '/flavourings'
      fullPath: '/flavourings'
      preLoaderRoute: typeof FlavouringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allergens': {
      id: '/allergens'
      path: '/allergens'
      fullPath: '/allergens'
      preLoaderRoute: typeof AllergensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additives': {
      id: '/additives'
      path: '/additives'
      fullPath: '/additives'
      preLoaderRoute: typeof AdditivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/additives_/$id': {
      id: '/additives_/$id'
      path: '/additives/$id'
      fullPath: '/additives/$id'
      preLoaderRoute: typeof AdditivesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProductsRouteRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  AdditivesRoute: AdditivesRoute,
  AllergensRoute: AllergensRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FlavouringsRoute: FlavouringsRoute,
  IngredientsClaimsRoute: IngredientsClaimsRoute,
  LabAverageRoute: LabAverageRoute,
  LabelingRoute: LabelingRoute,
  NutritionRoute: NutritionRoute,
  PackagingRoute: PackagingRoute,
  ProcessHaccpRoute: ProcessHaccpRoute,
  AdditivesIdRoute: AdditivesIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
