/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RawMaterialsRouteImport } from './routes/raw-materials'
import { Route as ProcessHaccpRouteImport } from './routes/process-haccp'
import { Route as PackagingRouteImport } from './routes/packaging'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LabelingRouteImport } from './routes/labeling'
import { Route as LabAverageRouteImport } from './routes/lab-average'
import { Route as IngredientsClaimsRouteImport } from './routes/ingredients-claims'
import { Route as FlavouringsRouteImport } from './routes/flavourings'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AllergensRouteImport } from './routes/allergens'
import { Route as AdditivesRouteImport } from './routes/additives'
import { Route as Products1RouteRouteImport } from './routes/products1.route'
import { Route as BrandsRouteRouteImport } from './routes/brands/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Products1IndexRouteImport } from './routes/products1.index'
import { Route as BrandsIndexRouteImport } from './routes/brands/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as Products1IdRouteImport } from './routes/products1.$id'
import { Route as AdditivesIdRouteImport } from './routes/additives_.$id'
import { Route as ProductsProductIdRouteRouteImport } from './routes/products/$productId/route'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'
import { Route as BrandsBrandIdIndexRouteImport } from './routes/brands/$brandId/index'
import { Route as ProductsProductIdRecipeRouteImport } from './routes/products/$productId/recipe'
import { Route as ProductsProductIdPackagingRouteImport } from './routes/products/$productId/packaging'
import { Route as ProductsProductIdNutritionRouteImport } from './routes/products/$productId/nutrition'
import { Route as ProductsProductIdLabResultsRouteImport } from './routes/products/$productId/lab-results'
import { Route as ProductsProductIdDocumentsRouteImport } from './routes/products/$productId/documents'
import { Route as ProductsProductIdAllergenRouteImport } from './routes/products/$productId/allergen'
import { Route as ProductsProductIdAdditivesRouteImport } from './routes/products/$productId/additives'

const RawMaterialsRoute = RawMaterialsRouteImport.update({
  id: '/raw-materials',
  path: '/raw-materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessHaccpRoute = ProcessHaccpRouteImport.update({
  id: '/process-haccp',
  path: '/process-haccp',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagingRoute = PackagingRouteImport.update({
  id: '/packaging',
  path: '/packaging',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelingRoute = LabelingRouteImport.update({
  id: '/labeling',
  path: '/labeling',
  getParentRoute: () => rootRouteImport,
} as any)
const LabAverageRoute = LabAverageRouteImport.update({
  id: '/lab-average',
  path: '/lab-average',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsClaimsRoute = IngredientsClaimsRouteImport.update({
  id: '/ingredients-claims',
  path: '/ingredients-claims',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavouringsRoute = FlavouringsRouteImport.update({
  id: '/flavourings',
  path: '/flavourings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AllergensRoute = AllergensRouteImport.update({
  id: '/allergens',
  path: '/allergens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdditivesRoute = AdditivesRouteImport.update({
  id: '/additives',
  path: '/additives',
  getParentRoute: () => rootRouteImport,
} as any)
const Products1RouteRoute = Products1RouteRouteImport.update({
  id: '/products1',
  path: '/products1',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRouteRoute = BrandsRouteRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Products1IndexRoute = Products1IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Products1RouteRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRouteRoute,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const Products1IdRoute = Products1IdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => Products1RouteRoute,
} as any)
const AdditivesIdRoute = AdditivesIdRouteImport.update({
  id: '/additives_/$id',
  path: '/additives/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRouteRoute = ProductsProductIdRouteRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsProductIdRouteRoute,
} as any)
const BrandsBrandIdIndexRoute = BrandsBrandIdIndexRouteImport.update({
  id: '/$brandId/',
  path: '/$brandId/',
  getParentRoute: () => BrandsRouteRoute,
} as any)
const ProductsProductIdRecipeRoute = ProductsProductIdRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => ProductsProductIdRouteRoute,
} as any)
const ProductsProductIdPackagingRoute =
  ProductsProductIdPackagingRouteImport.update({
    id: '/packaging',
    path: '/packaging',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)
const ProductsProductIdNutritionRoute =
  ProductsProductIdNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)
const ProductsProductIdLabResultsRoute =
  ProductsProductIdLabResultsRouteImport.update({
    id: '/lab-results',
    path: '/lab-results',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)
const ProductsProductIdDocumentsRoute =
  ProductsProductIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)
const ProductsProductIdAllergenRoute =
  ProductsProductIdAllergenRouteImport.update({
    id: '/allergen',
    path: '/allergen',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)
const ProductsProductIdAdditivesRoute =
  ProductsProductIdAdditivesRouteImport.update({
    id: '/additives',
    path: '/additives',
    getParentRoute: () => ProductsProductIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteRouteWithChildren
  '/products1': typeof Products1RouteRouteWithChildren
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/products/$productId': typeof ProductsProductIdRouteRouteWithChildren
  '/additives/$id': typeof AdditivesIdRoute
  '/products1/$id': typeof Products1IdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/brands/': typeof BrandsIndexRoute
  '/products1/': typeof Products1IndexRoute
  '/products/$productId/additives': typeof ProductsProductIdAdditivesRoute
  '/products/$productId/allergen': typeof ProductsProductIdAllergenRoute
  '/products/$productId/documents': typeof ProductsProductIdDocumentsRoute
  '/products/$productId/lab-results': typeof ProductsProductIdLabResultsRoute
  '/products/$productId/nutrition': typeof ProductsProductIdNutritionRoute
  '/products/$productId/packaging': typeof ProductsProductIdPackagingRoute
  '/products/$productId/recipe': typeof ProductsProductIdRecipeRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/additives/$id': typeof AdditivesIdRoute
  '/products1/$id': typeof Products1IdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/brands': typeof BrandsIndexRoute
  '/products1': typeof Products1IndexRoute
  '/products/$productId/additives': typeof ProductsProductIdAdditivesRoute
  '/products/$productId/allergen': typeof ProductsProductIdAllergenRoute
  '/products/$productId/documents': typeof ProductsProductIdDocumentsRoute
  '/products/$productId/lab-results': typeof ProductsProductIdLabResultsRoute
  '/products/$productId/nutrition': typeof ProductsProductIdNutritionRoute
  '/products/$productId/packaging': typeof ProductsProductIdPackagingRoute
  '/products/$productId/recipe': typeof ProductsProductIdRecipeRoute
  '/brands/$brandId': typeof BrandsBrandIdIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brands': typeof BrandsRouteRouteWithChildren
  '/products1': typeof Products1RouteRouteWithChildren
  '/additives': typeof AdditivesRoute
  '/allergens': typeof AllergensRoute
  '/dashboard': typeof DashboardRoute
  '/flavourings': typeof FlavouringsRoute
  '/ingredients-claims': typeof IngredientsClaimsRoute
  '/lab-average': typeof LabAverageRoute
  '/labeling': typeof LabelingRoute
  '/nutrition': typeof NutritionRoute
  '/packaging': typeof PackagingRoute
  '/process-haccp': typeof ProcessHaccpRoute
  '/raw-materials': typeof RawMaterialsRoute
  '/products/$productId': typeof ProductsProductIdRouteRouteWithChildren
  '/additives_/$id': typeof AdditivesIdRoute
  '/products1/$id': typeof Products1IdRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/brands/': typeof BrandsIndexRoute
  '/products1/': typeof Products1IndexRoute
  '/products/$productId/additives': typeof ProductsProductIdAdditivesRoute
  '/products/$productId/allergen': typeof ProductsProductIdAllergenRoute
  '/products/$productId/documents': typeof ProductsProductIdDocumentsRoute
  '/products/$productId/lab-results': typeof ProductsProductIdLabResultsRoute
  '/products/$productId/nutrition': typeof ProductsProductIdNutritionRoute
  '/products/$productId/packaging': typeof ProductsProductIdPackagingRoute
  '/products/$productId/recipe': typeof ProductsProductIdRecipeRoute
  '/brands/$brandId/': typeof BrandsBrandIdIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brands'
    | '/products1'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/raw-materials'
    | '/products/$productId'
    | '/additives/$id'
    | '/products1/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/brands/'
    | '/products1/'
    | '/products/$productId/additives'
    | '/products/$productId/allergen'
    | '/products/$productId/documents'
    | '/products/$productId/lab-results'
    | '/products/$productId/nutrition'
    | '/products/$productId/packaging'
    | '/products/$productId/recipe'
    | '/brands/$brandId/'
    | '/products/$productId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/raw-materials'
    | '/additives/$id'
    | '/products1/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/brands'
    | '/products1'
    | '/products/$productId/additives'
    | '/products/$productId/allergen'
    | '/products/$productId/documents'
    | '/products/$productId/lab-results'
    | '/products/$productId/nutrition'
    | '/products/$productId/packaging'
    | '/products/$productId/recipe'
    | '/brands/$brandId'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/brands'
    | '/products1'
    | '/additives'
    | '/allergens'
    | '/dashboard'
    | '/flavourings'
    | '/ingredients-claims'
    | '/lab-average'
    | '/labeling'
    | '/nutrition'
    | '/packaging'
    | '/process-haccp'
    | '/raw-materials'
    | '/products/$productId'
    | '/additives_/$id'
    | '/products1/$id'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/brands/'
    | '/products1/'
    | '/products/$productId/additives'
    | '/products/$productId/allergen'
    | '/products/$productId/documents'
    | '/products/$productId/lab-results'
    | '/products/$productId/nutrition'
    | '/products/$productId/packaging'
    | '/products/$productId/recipe'
    | '/brands/$brandId/'
    | '/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandsRouteRoute: typeof BrandsRouteRouteWithChildren
  Products1RouteRoute: typeof Products1RouteRouteWithChildren
  AdditivesRoute: typeof AdditivesRoute
  AllergensRoute: typeof AllergensRoute
  DashboardRoute: typeof DashboardRoute
  FlavouringsRoute: typeof FlavouringsRoute
  IngredientsClaimsRoute: typeof IngredientsClaimsRoute
  LabAverageRoute: typeof LabAverageRoute
  LabelingRoute: typeof LabelingRoute
  NutritionRoute: typeof NutritionRoute
  PackagingRoute: typeof PackagingRoute
  ProcessHaccpRoute: typeof ProcessHaccpRoute
  RawMaterialsRoute: typeof RawMaterialsRoute
  ProductsProductIdRouteRoute: typeof ProductsProductIdRouteRouteWithChildren
  AdditivesIdRoute: typeof AdditivesIdRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/raw-materials': {
      id: '/raw-materials'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof RawMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process-haccp': {
      id: '/process-haccp'
      path: '/process-haccp'
      fullPath: '/process-haccp'
      preLoaderRoute: typeof ProcessHaccpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packaging': {
      id: '/packaging'
      path: '/packaging'
      fullPath: '/packaging'
      preLoaderRoute: typeof PackagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labeling': {
      id: '/labeling'
      path: '/labeling'
      fullPath: '/labeling'
      preLoaderRoute: typeof LabelingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-average': {
      id: '/lab-average'
      path: '/lab-average'
      fullPath: '/lab-average'
      preLoaderRoute: typeof LabAverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients-claims': {
      id: '/ingredients-claims'
      path: '/ingredients-claims'
      fullPath: '/ingredients-claims'
      preLoaderRoute: typeof IngredientsClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavourings': {
      id: '/flavourings'
      path: '/flavourings'
      fullPath: '/flavourings'
      preLoaderRoute: typeof FlavouringsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allergens': {
      id: '/allergens'
      path: '/allergens'
      fullPath: '/allergens'
      preLoaderRoute: typeof AllergensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/additives': {
      id: '/additives'
      path: '/additives'
      fullPath: '/additives'
      preLoaderRoute: typeof AdditivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products1': {
      id: '/products1'
      path: '/products1'
      fullPath: '/products1'
      preLoaderRoute: typeof Products1RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products1/': {
      id: '/products1/'
      path: '/'
      fullPath: '/products1/'
      preLoaderRoute: typeof Products1IndexRouteImport
      parentRoute: typeof Products1RouteRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRouteRoute
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products1/$id': {
      id: '/products1/$id'
      path: '/$id'
      fullPath: '/products1/$id'
      preLoaderRoute: typeof Products1IdRouteImport
      parentRoute: typeof Products1RouteRoute
    }
    '/additives_/$id': {
      id: '/additives_/$id'
      path: '/additives/$id'
      fullPath: '/additives/$id'
      preLoaderRoute: typeof AdditivesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/'
      fullPath: '/products/$productId/'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/brands/$brandId/': {
      id: '/brands/$brandId/'
      path: '/$brandId'
      fullPath: '/brands/$brandId/'
      preLoaderRoute: typeof BrandsBrandIdIndexRouteImport
      parentRoute: typeof BrandsRouteRoute
    }
    '/products/$productId/recipe': {
      id: '/products/$productId/recipe'
      path: '/recipe'
      fullPath: '/products/$productId/recipe'
      preLoaderRoute: typeof ProductsProductIdRecipeRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/packaging': {
      id: '/products/$productId/packaging'
      path: '/packaging'
      fullPath: '/products/$productId/packaging'
      preLoaderRoute: typeof ProductsProductIdPackagingRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/nutrition': {
      id: '/products/$productId/nutrition'
      path: '/nutrition'
      fullPath: '/products/$productId/nutrition'
      preLoaderRoute: typeof ProductsProductIdNutritionRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/lab-results': {
      id: '/products/$productId/lab-results'
      path: '/lab-results'
      fullPath: '/products/$productId/lab-results'
      preLoaderRoute: typeof ProductsProductIdLabResultsRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/documents': {
      id: '/products/$productId/documents'
      path: '/documents'
      fullPath: '/products/$productId/documents'
      preLoaderRoute: typeof ProductsProductIdDocumentsRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/allergen': {
      id: '/products/$productId/allergen'
      path: '/allergen'
      fullPath: '/products/$productId/allergen'
      preLoaderRoute: typeof ProductsProductIdAllergenRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
    '/products/$productId/additives': {
      id: '/products/$productId/additives'
      path: '/additives'
      fullPath: '/products/$productId/additives'
      preLoaderRoute: typeof ProductsProductIdAdditivesRouteImport
      parentRoute: typeof ProductsProductIdRouteRoute
    }
  }
}

interface BrandsRouteRouteChildren {
  BrandsIndexRoute: typeof BrandsIndexRoute
  BrandsBrandIdIndexRoute: typeof BrandsBrandIdIndexRoute
}

const BrandsRouteRouteChildren: BrandsRouteRouteChildren = {
  BrandsIndexRoute: BrandsIndexRoute,
  BrandsBrandIdIndexRoute: BrandsBrandIdIndexRoute,
}

const BrandsRouteRouteWithChildren = BrandsRouteRoute._addFileChildren(
  BrandsRouteRouteChildren,
)

interface Products1RouteRouteChildren {
  Products1IdRoute: typeof Products1IdRoute
  Products1IndexRoute: typeof Products1IndexRoute
}

const Products1RouteRouteChildren: Products1RouteRouteChildren = {
  Products1IdRoute: Products1IdRoute,
  Products1IndexRoute: Products1IndexRoute,
}

const Products1RouteRouteWithChildren = Products1RouteRoute._addFileChildren(
  Products1RouteRouteChildren,
)

interface ProductsProductIdRouteRouteChildren {
  ProductsProductIdAdditivesRoute: typeof ProductsProductIdAdditivesRoute
  ProductsProductIdAllergenRoute: typeof ProductsProductIdAllergenRoute
  ProductsProductIdDocumentsRoute: typeof ProductsProductIdDocumentsRoute
  ProductsProductIdLabResultsRoute: typeof ProductsProductIdLabResultsRoute
  ProductsProductIdNutritionRoute: typeof ProductsProductIdNutritionRoute
  ProductsProductIdPackagingRoute: typeof ProductsProductIdPackagingRoute
  ProductsProductIdRecipeRoute: typeof ProductsProductIdRecipeRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

const ProductsProductIdRouteRouteChildren: ProductsProductIdRouteRouteChildren =
  {
    ProductsProductIdAdditivesRoute: ProductsProductIdAdditivesRoute,
    ProductsProductIdAllergenRoute: ProductsProductIdAllergenRoute,
    ProductsProductIdDocumentsRoute: ProductsProductIdDocumentsRoute,
    ProductsProductIdLabResultsRoute: ProductsProductIdLabResultsRoute,
    ProductsProductIdNutritionRoute: ProductsProductIdNutritionRoute,
    ProductsProductIdPackagingRoute: ProductsProductIdPackagingRoute,
    ProductsProductIdRecipeRoute: ProductsProductIdRecipeRoute,
    ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
  }

const ProductsProductIdRouteRouteWithChildren =
  ProductsProductIdRouteRoute._addFileChildren(
    ProductsProductIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandsRouteRoute: BrandsRouteRouteWithChildren,
  Products1RouteRoute: Products1RouteRouteWithChildren,
  AdditivesRoute: AdditivesRoute,
  AllergensRoute: AllergensRoute,
  DashboardRoute: DashboardRoute,
  FlavouringsRoute: FlavouringsRoute,
  IngredientsClaimsRoute: IngredientsClaimsRoute,
  LabAverageRoute: LabAverageRoute,
  LabelingRoute: LabelingRoute,
  NutritionRoute: NutritionRoute,
  PackagingRoute: PackagingRoute,
  ProcessHaccpRoute: ProcessHaccpRoute,
  RawMaterialsRoute: RawMaterialsRoute,
  ProductsProductIdRouteRoute: ProductsProductIdRouteRouteWithChildren,
  AdditivesIdRoute: AdditivesIdRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
